sample_project:
  target: test
  outputs:
    prod:
      type: duckdb
      path: /tmp/prefect_dbt_flow_prod.duckdb
    dev:
      type: duckdb
      path: /tmp/prefect_dbt_flow_dev.duckdb
    test:
      type: duckdb
      path: "{{ env_var('DUCKDB_DB_FILE') }}"
    override_in_test:
      type: duckdb
      path: /does/not/exist/so/override.duckdb
