sample_project:
  target: dev
  outputs:
    dev:
      type: postgres
      host: db
      user: admin
      password: admin
      port: 5432
      dbname: test_db
      schema: test_schema
    prod:
      type: postgres
      host: db
      user: admin
      password: admin
      port: 5432
      dbname: test_db
      schema: test_schema
