site_name: "prefect-dbt-flow"
site_description: "Docummentation for `prefect_dbt_flow."
site_url: "https://datarootsio.github.io/prefect-dbt-flow"
repo_url: "https://github.com/datarootsio/prefect-dbt-flow"
edit_uri: "blob/main/docs/"
repo_name: "datarootsio/prefect-dbt-flow"

markdown_extensions:
  - def_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.tasklist:
      custom_checkbox: true

theme:
  name: "material"
  # logo: images/sm-logo-white.png
  # favicon: images/sm-logo.png
  font:
    text: arvo
    code: poppins
  icon:
    repo: fontawesome/brands/github-alt
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top

plugins:
  - search
  - autorefs
  - coverage
  - mkdocstrings:
      handlers:
        python:
          options:
            heading_level: 3
            show_root_heading: true

extra_css:
  - stylesheets/extra.css

nav:
  - Home:
      - Overview: index.md
      - Getting started: getting_started.md
      - How it works: how_it_works.md
      - Changelog: https://github.com/datarootsio/prefect-dbt-flow/releases
      - License: license.md
  - API:
      - dbt Flow: api/flow.md
      - dbt Models: api/models.md
      - dbt Tasks: api/tasks.md
      - dbt Graph: api/graph.md
      - dbt CLI: api/cli.md

copyright: "Maintained by dataroots"

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github-alt
      link: "https://github.com/datarootsio"
    - icon: fontawesome/brands/linkedin
      link: "https://www.linkedin.com/company/dataroots/"
    - icon: fontawesome/brands/instagram
      link: "https://www.instagram.com/lifeatdataroots/"
    - icon: fontawesome/brands/youtube
      link: "https://www.youtube.com/c/dataroots"
    - icon: fontawesome/solid/globe
      link: "https://dataroots.io/"
