name: 'tests'
on: [push, pull_request]

jobs:
  linting:
    env:
      POETRY_VERSION: 1.5.1
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: setup poetry
        run: |
          pip install poetry==${{ env.POETRY_VERSION }} 
          poetry config virtualenvs.create false
          poetry install --no-interaction --no-ansi
      - name: run precommit hooks
        run: pre-commit run --all-files
  tests:
    env:
      POETRY_VERSION: 1.5.1
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: setup poetry
        run: |
          pip install poetry==${{ env.POETRY_VERSION }} 
          poetry config virtualenvs.create false
          poetry install --no-interaction --no-ansi
      - name: run pytest
        run: poetry run pytest